gymequip/config/routes.rb
Rails.application.routes.draw do
  
  get 'filter/index'
  get 'filter/results'
  get 'categories/show'
  get 'pages/show'
  get 'product/index'
  get 'product/show'
  resources :product ,only:[:index,:show]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :filter , only:[:index] do
    collection do
      get 'results'
    end
  end

  root to: 'product#index'
  get '/:permalink' , to: 'pages#permalink' , as: 'permalink'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

gymequip/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

gymequip/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

gymequip/app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

gymequip/app/models/page.rb
class Page < ApplicationRecord
end

gymequip/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :product_status

  mount_uploader :image, ImageUploader
end

gymequip/app/models/product_status.rb
class ProductStatus < ApplicationRecord
    has_many :products
end

gymequip/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

gymequip/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    id = Category.find(params[:id])
    @products = id.products
  end
end

gymequip/app/controllers/filter_controller.rb
class FilterController < ApplicationController
  def index
  end

  def results
    if params[:query_status][:product_status_id].empty?
      @products = Product.all
    else
      product_status = ProductStatus.find(params[:query_status][:product_status_id])
      @products = product_status.products.where(product_status_id: product_status)

      @name = @products.first.product_status.name
    end
  end
end

gymequip/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def permalink
    @page = Page.find_by(permalink: params[:permalink])

    if @page.nil?
      redirect_to root_url
    else
      render :show
    end
  end

  def show
    @page = Page.find(params[:id])
  end
end

gymequip/app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

gymequip/app/helpers/application_helper.rb
module ApplicationHelper
end

gymequip/app/helpers/categories_helper.rb
module CategoriesHelper
end

gymequip/app/helpers/filter_helper.rb
module FilterHelper
end

gymequip/app/helpers/pages_helper.rb
module PagesHelper
end

gymequip/app/helpers/product_helper.rb
module ProductHelper
end

gymequip/app/views/categories/show.html.erb
<h1>Products</h1>

<% @products.each do |p| %>

<%= link_to p.name, p %><br>
<%= p.price %><br>
<%= p.category.name%><br>
<br>
<% end%>

gymequip/app/views/filter/index.html.erb
<h1>Filter#index</h1>
<p>Find me in app/views/filter/index.html.erb</p>

gymequip/app/views/filter/results.html.erb
<h1><%=@name%> Products</h1>

<% @products.each do |p| %>

<%= link_to p.name, p %><br>
<%= p.price %><br>
<%= p.category.name%><br>
<br>
<% end%>

gymequip/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gymequip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% pages = Page.all%>
    <% pages.each do |p| %>
      <%= link_to "#{p.title}", permalink_path(:permalink => p.permalink) %><br>
    <%end %>
    <br>
    <h3>Categories</h3>
      <% category = Category.all %>
      <% category.each do |c| %>
      <%= link_to "#{c.name}", categories_show_path(:id => c.id) %><br>
      <% end %>
    <br>
    <h3>Filter Products</h3>
    <%= form_tag(results_filter_index_path, method: "get") do %>
    <%= label_tag(:query, "Filter:") %>
    <%= collection_select(:query_status,:product_status_id,ProductStatus.all.order(:name),:id,:name)%>
    <%= submit_tag("Filter Products") %>
    <% end %>
    <%= yield %>
  </body>
</html>

gymequip/app/views/pages/permalink.html.erb
<h1>Pages#permalink</h1>
<p>Find me in app/views/pages/permalink.html.erb</p>

gymequip/app/views/pages/show.html.erb
<h1><%= @page.title %></h1>
<p><%= @page.content%></p>

gymequip/app/views/product/index.html.erb
<h1>Products</h1>


<% @products.each do |p| %>

<%= link_to p.name, p %><br>
<%= p.price %><br>
<%= p.category.name%><br>
<br>
<% end%>

gymequip/app/views/product/show.html.erb
<h1>Product Details</h1>

<% if @product.image.present? %>
 <p><%= image_tag @product.image.url , width: 200 %></p>
<% end %>

<p><%= @product.name%></p>
<p>$ <%= @product.price%></p>
<p><%= @product.description%></p>
<p><%= @product.category.name%></p>